modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "oelib"
version = "${version}"
displayName = "OELib"
authors = "Flechazo"
description = "Mafuyu never like you:("

logoFile = "icon3.png"

[[dependencies.oelib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oelib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "oelib.mixins.json"
[[mixins]]
config = "oelib.forge.mixins.json"
