plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    annotationProcessor project(path: ':common')
    implementation("org.mvel:mvel2:2.5.0.Final")
    implementation(include("cn.6tail:lunar:1.7.3"))
    implementation(include("com.electronwill.night-config:core:3.8.3"))
    implementation(include("com.electronwill.night-config:toml:3.8.3"))
    implementation(include("de.marhali:json5-java:3.0.0"))

    implementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}")
}

// Allow by `group`, `artifact`, or full `group:artifact`.
// Add an item here to keep that dependency in the published POM.
mavenDependencyWhitelist = [
        'cn.6tail:lunar',
        'de.marhali:json5-java',
        'com.electronwill.night-config:core',
        'com.electronwill.night-config:toml',
        'org.mvel:mvel2'
]

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

publishing {
    repositories {
        def modVersion = project.version ?: 'unknown'
        boolean isSnapshot = modVersion.toLowerCase().contains('snapshot')
        def publishUrl = isSnapshot ?
                "https://maven.sighs.cc/repository/maven-snapshots/" :
                "https://maven.sighs.cc/repository/maven-releases/"

        maven {
            name = "remoteRepo"
            url = uri(publishUrl)
            credentials {
                username = System.getenv("SIGHS_PUBLISH_USER")
                password = System.getenv("SIGHS_PUBLISH_PASSWORD")
            }
        }
    }

    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group
            artifactId = base.archivesName.get()
            version = project.version

            applyPomDependencyWhitelist(delegate as MavenPublication)
        }
    }
}
