plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    modImplementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"
    modImplementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}")
    modImplementation("mezz.jei:jei-$rootProject.minecraft_version-fabric:${jei_version}")

    common(project(path: ':common-api', configuration: 'namedElements')) { transitive false }
    shadowCommon (project(path: ':common-api', configuration: 'transformProductionFabric')) { transitive false }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

jar {
    archiveClassifier = "dev"
}

java {
    withSourcesJar()
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = base.archivesName.get()
            artifact(remapJar) {
                builtBy tasks.remapJar
                classifier null
            }
            artifact(tasks.sourcesJar) {
                classifier "sources"
            }
        }
    }
}

// 此开发环境运行时无法识别 MVEL，很神秘
tasks.named("runClient") {
    systemProperty "oelib.skipExpressionEngine", "true"
}