# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
# Mod properties
mod_version=0.0.7-beta1-SNAPSHOT
maven_group=cc.sighs.oelib
archives_name=OELib
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.17.2
fabric_api_version=0.116.5+1.21.1
neoforge_version=21.1.215
modmenu_version=11.0.3
jei_version=19.22.1.316
