
plugins {
    id 'com.github.johnrengelman.shadow'
}

loom {
    forge {
        mixinConfig "oelib.mixins.json"
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"
    common(project(path: ':common-api', configuration: 'namedElements')) { transitive false }
    shadowCommon (project(path: ':common-api', configuration: 'transformProductionForge')) { transitive false }

    modImplementation("mezz.jei:jei-$rootProject.minecraft_version-forge:${jei_version}")
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

def modRuntime(str) {
    dependencies.modLocalRuntime(str)
}


components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

jar {
    archiveClassifier = "dev"
}

java {
    withSourcesJar()
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = base.archivesName.get()
            artifact(remapJar) {
                builtBy tasks.remapJar
                classifier null
            }
            artifact(tasks.sourcesJar) {
                classifier "sources"
            }
        }
    }
}

// 此开发环境运行时无法识别 MVEL，很神秘
tasks.named("runClient") {
    systemProperty "oelib.skipExpressionEngine", "true"
}
