modLoader = "javafml"
loaderVersion = "[1,)" # NeoForge FML4+
license = "MIT"
showAsResourcePack = false

[[mods]]
modId = "oelib_common_api"
version = "${version}"
displayName = "OELib Common API (Fake)"
description = "Fake mod marker for common-api to allow nested jars."