package cc.sighs.oelib.config.util;

import java.lang.classfile.ClassFile;
import java.lang.classfile.CodeBuilder;
import java.lang.classfile.TypeKind;
import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.RecordComponent;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Generates hidden classes for zero-overhead record component access.
 *
 * <p>This utility uses the Class-File API to emit a hidden class per
 * (record class, target component) pair. The generated class contains two
 * static methods: {@code view} (reads the component) and {@code update}
 * (creates a new record with the component replaced). Method handles to
 * these methods are returned as {@link GeneratedLensAccessors}.
 *
 * <p>The generated bytecode uses {@code invokedynamic} / {@code invokevirtual}
 * for component access and {@code new}/{@code invokespecial} for record
 * construction, avoiding reflection overhead on hot paths.
 */
public final class RecordLensClassGenerator {
    private static final AtomicLong COUNTER = new AtomicLong();

    private RecordLensClassGenerator() {
    }

    /**
     * Generates accessors for a single record component using the
     * caller's lookup.
     *
     * @param recordClass the record class
     * @param components  the record's components
     * @param targetIndex the index of the component to target
     * @return the generated accessors
     * @throws IllegalStateException if generation fails
     */
    public static GeneratedLensAccessors generate(Class<?> recordClass, RecordComponent[] components, int targetIndex) {
        return generate(recordClass, components, targetIndex, MethodHandles.lookup());
    }

    /**
     * Generates accessors for a single record component using an
     * explicit lookup.
     *
     * @param recordClass the record class
     * @param components  the record's components
     * @param targetIndex the index of the component to target
     * @param lookup      the lookup for access control
     * @return the generated accessors
     * @throws IllegalArgumentException if {@code lookup} is {@code null}
     * @throws IllegalStateException    if generation fails
     */
    public static GeneratedLensAccessors generate(Class<?> recordClass, RecordComponent[] components, int targetIndex, MethodHandles.Lookup lookup) {
        if (lookup == null) {
            throw new IllegalArgumentException("lookup cannot be null");
        }
        try {
            MethodHandles.Lookup privateLookup = MethodHandles.privateLookupIn(recordClass, lookup);
            Class<?> targetType = components[targetIndex].getType();

            String generatedBinaryName = generatedBinaryName(recordClass);
            ClassDesc generatedClass = ClassDesc.of(generatedBinaryName);
            ClassDesc recordClassDesc = classDesc(recordClass);
            MethodTypeDesc initType = MethodTypeDesc.ofDescriptor("()V");
            MethodTypeDesc viewType = methodType(targetType, recordClass);
            MethodTypeDesc updateType = methodType(recordClass, targetType, recordClass);
            MethodTypeDesc recordCtorType = methodType(void.class, componentTypes(components));

            byte[] bytes = ClassFile.of().build(generatedClass, clb -> {
                clb.withFlags(ClassFile.ACC_FINAL | ClassFile.ACC_SYNTHETIC);
                clb.withSuperclass(ConstantDescs.CD_Object);

                clb.withMethodBody("<init>", initType, ClassFile.ACC_PRIVATE, code -> {
                    code.aload(0);
                    code.invokespecial(ConstantDescs.CD_Object, "<init>", initType);
                    code.return_();
                });

                clb.withMethodBody("view", viewType, ClassFile.ACC_STATIC | ClassFile.ACC_FINAL | ClassFile.ACC_SYNTHETIC, code -> {
                    code.aload(0);
                    code.invokevirtual(recordClassDesc, components[targetIndex].getName(), MethodTypeDesc.of(classDesc(targetType)));
                    emitReturn(code, targetType);
                });

                clb.withMethodBody("update", updateType, ClassFile.ACC_STATIC | ClassFile.ACC_FINAL | ClassFile.ACC_SYNTHETIC, code -> {
                    code.new_(recordClassDesc);
                    code.dup();
                    int sourceSlot = localSlotSize(targetType);
                    for (int i = 0; i < components.length; i++) {
                        Class<?> componentType = components[i].getType();
                        if (i == targetIndex) {
                            emitLoad(code, componentType, 0);
                        } else {
                            code.aload(sourceSlot);
                            code.invokevirtual(recordClassDesc, components[i].getName(), MethodTypeDesc.of(classDesc(componentType)));
                        }
                    }
                    code.invokespecial(recordClassDesc, "<init>", recordCtorType);
                    code.areturn();
                });
            });

            MethodHandles.Lookup hiddenLookup = privateLookup.defineHiddenClass(
                    bytes,
                    true,
                    MethodHandles.Lookup.ClassOption.NESTMATE
            );
            Class<?> hiddenClass = hiddenLookup.lookupClass();
            MethodHandle view = hiddenLookup.findStatic(hiddenClass, "view", MethodType.methodType(targetType, recordClass));
            MethodHandle update = hiddenLookup.findStatic(hiddenClass, "update", MethodType.methodType(recordClass, targetType, recordClass));
            return new GeneratedLensAccessors(
                    view.asType(MethodType.methodType(Object.class, Object.class)),
                    update.asType(MethodType.methodType(Object.class, Object.class, Object.class))
            );
        } catch (Throwable t) {
            throw new IllegalStateException("Failed to generate hidden lens helpers for " + recordClass.getName(), t);
        }
    }

    /**
     * Generates accessors for a nested path of record components using the
     * caller's lookup.
     *
     * @param rootClass     the root record class
     * @param componentPath the path of component names from root to leaf
     * @return the generated accessors
     */
    public static GeneratedLensAccessors generatePath(Class<?> rootClass, String[] componentPath) {
        return generatePath(rootClass, componentPath, MethodHandles.lookup());
    }

    /**
     * Generates accessors for a nested path of record components using an
     * explicit lookup.
     *
     * @param rootClass     the root record class
     * @param componentPath the path of component names from root to leaf
     * @param lookup        the lookup for access control
     * @return the generated accessors
     * @throws IllegalArgumentException if {@code lookup} is {@code null}
     * @throws IllegalStateException    if generation fails
     */
    public static GeneratedLensAccessors generatePath(Class<?> rootClass, String[] componentPath, MethodHandles.Lookup lookup) {
        if (lookup == null) {
            throw new IllegalArgumentException("lookup cannot be null");
        }
        try {
            PathResolution resolution = resolvePath(rootClass, componentPath);
            MethodHandles.Lookup privateLookup = MethodHandles.privateLookupIn(rootClass, lookup);

            String generatedBinaryName = generatedBinaryName(rootClass) + "$Path";
            ClassDesc generatedClass = ClassDesc.of(generatedBinaryName);
            ClassDesc rootClassDesc = classDesc(rootClass);
            ClassDesc leafClassDesc = classDesc(resolution.leafType());
            MethodTypeDesc initType = MethodTypeDesc.ofDescriptor("()V");
            MethodTypeDesc viewType = methodType(resolution.leafType(), rootClass);
            MethodTypeDesc updateType = methodType(rootClass, resolution.leafType(), rootClass);

            byte[] bytes = ClassFile.of().build(generatedClass, clb -> {
                clb.withFlags(ClassFile.ACC_FINAL | ClassFile.ACC_SYNTHETIC);
                clb.withSuperclass(ConstantDescs.CD_Object);

                clb.withMethodBody("<init>", initType, ClassFile.ACC_PRIVATE, code -> {
                    code.aload(0);
                    code.invokespecial(ConstantDescs.CD_Object, "<init>", initType);
                    code.return_();
                });

                clb.withMethodBody("view", viewType, ClassFile.ACC_STATIC | ClassFile.ACC_FINAL | ClassFile.ACC_SYNTHETIC, code -> {
                    code.aload(0);
                    for (int i = 0; i < resolution.components().length; i++) {
                        Class<?> owner = resolution.owners()[i];
                        RecordComponent component = resolution.components()[i];
                        code.invokevirtual(classDesc(owner), component.getName(), MethodTypeDesc.of(classDesc(component.getType())));
                    }
                    emitReturn(code, resolution.leafType());
                });

                clb.withMethodBody("update", updateType, ClassFile.ACC_STATIC | ClassFile.ACC_FINAL | ClassFile.ACC_SYNTHETIC, code -> {
                    int sourceSlot = localSlotSize(resolution.leafType());
                    int depth = resolution.components().length;

                    int[] ownerSlots = new int[depth];
                    ownerSlots[0] = sourceSlot;
                    int nextSlot = sourceSlot + 1;
                    for (int i = 1; i < depth; i++) {
                        ownerSlots[i] = nextSlot++;
                    }

                    int[] rebuiltSlots = new int[depth];
                    for (int i = depth - 1; i >= 0; i--) {
                        rebuiltSlots[i] = nextSlot++;
                    }

                    for (int i = 1; i < depth; i++) {
                        code.aload(ownerSlots[i - 1]);
                        RecordComponent toChild = resolution.components()[i - 1];
                        code.invokevirtual(classDesc(resolution.owners()[i - 1]), toChild.getName(), MethodTypeDesc.of(classDesc(toChild.getType())));
                        code.astore(ownerSlots[i]);
                    }

                    for (int i = depth - 1; i >= 0; i--) {
                        Class<?> owner = resolution.owners()[i];
                        RecordComponent targetComponent = resolution.components()[i];
                        RecordComponent[] ownerComponents = owner.getRecordComponents();

                        code.new_(classDesc(owner));
                        code.dup();
                        for (RecordComponent component : ownerComponents) {
                            if (component.getName().equals(targetComponent.getName())) {
                                if (i == depth - 1) {
                                    emitLoad(code, resolution.leafType(), 0);
                                } else {
                                    code.aload(rebuiltSlots[i + 1]);
                                }
                            } else {
                                code.aload(ownerSlots[i]);
                                code.invokevirtual(classDesc(owner), component.getName(), MethodTypeDesc.of(classDesc(component.getType())));
                            }
                        }
                        code.invokespecial(classDesc(owner), "<init>", methodType(void.class, componentTypes(ownerComponents)));
                        code.astore(rebuiltSlots[i]);
                    }

                    code.aload(rebuiltSlots[0]);
                    code.areturn();
                });
            });

            MethodHandles.Lookup hiddenLookup = privateLookup.defineHiddenClass(
                    bytes,
                    true,
                    MethodHandles.Lookup.ClassOption.NESTMATE
            );
            Class<?> hiddenClass = hiddenLookup.lookupClass();
            MethodHandle view = hiddenLookup.findStatic(hiddenClass, "view", MethodType.methodType(resolution.leafType(), rootClass));
            MethodHandle update = hiddenLookup.findStatic(hiddenClass, "update", MethodType.methodType(rootClass, resolution.leafType(), rootClass));
            return new GeneratedLensAccessors(
                    view.asType(MethodType.methodType(Object.class, Object.class)),
                    update.asType(MethodType.methodType(Object.class, Object.class, Object.class))
            );
        } catch (Throwable t) {
            throw new IllegalStateException("Failed to generate hidden path lens for " + rootClass.getName(), t);
        }
    }

    private static String generatedBinaryName(Class<?> recordClass) {
        return recordClass.getName() + "$OELibLens$" + COUNTER.incrementAndGet();
    }

    private static Class<?>[] componentTypes(RecordComponent[] components) {
        Class<?>[] types = new Class<?>[components.length];
        for (int i = 0; i < components.length; i++) {
            types[i] = components[i].getType();
        }
        return types;
    }

    private static PathResolution resolvePath(Class<?> rootClass, String[] componentPath) {
        if (componentPath.length == 0) {
            throw new IllegalArgumentException("Record path cannot be empty");
        }
        Class<?>[] owners = new Class<?>[componentPath.length];
        RecordComponent[] components = new RecordComponent[componentPath.length];
        Class<?> owner = rootClass;
        for (int i = 0; i < componentPath.length; i++) {
            if (!owner.isRecord()) {
                throw new IllegalArgumentException("Non-record encountered in path: " + owner.getName());
            }
            RecordComponent component = findComponent(owner, componentPath[i]);
            owners[i] = owner;
            components[i] = component;
            owner = component.getType();
        }
        return new PathResolution(owners, components, owner);
    }

    private static RecordComponent findComponent(Class<?> owner, String name) {
        for (RecordComponent component : owner.getRecordComponents()) {
            if (component.getName().equals(name)) {
                return component;
            }
        }
        throw new IllegalArgumentException("Unknown component '" + name + "' in " + owner.getName());
    }

    private static MethodTypeDesc methodType(Class<?> returnType, Class<?>... params) {
        StringBuilder desc = new StringBuilder("(");
        for (Class<?> param : params) {
            desc.append(param.descriptorString());
        }
        desc.append(')').append(returnType.descriptorString());
        return MethodTypeDesc.ofDescriptor(desc.toString());
    }

    private static ClassDesc classDesc(Class<?> type) {
        return type.describeConstable()
                .orElseThrow(() -> new IllegalStateException("Cannot describe type " + type.getName()));
    }

    private static int localSlotSize(Class<?> type) {
        return type == long.class || type == double.class ? 2 : 1;
    }

    private static void emitLoad(CodeBuilder code, Class<?> type, int slot) {
        TypeKind kind = TypeKind.fromDescriptor(type.descriptorString()).asLoadable();
        code.loadLocal(kind, slot);
    }

    private static void emitReturn(CodeBuilder code, Class<?> type) {
        TypeKind kind = TypeKind.fromDescriptor(type.descriptorString()).asLoadable();
        code.return_(kind);
    }

    /**
     * A pair of method handles for viewing and updating a record component.
     *
     * @param view   a method handle {@code (Object) -> Object} that reads the component
     * @param update a method handle {@code (Object, Object) -> Object} that replaces
     *               the component and returns a new record
     */
    public record GeneratedLensAccessors(MethodHandle view, MethodHandle update) {
    }

    private record PathResolution(Class<?>[] owners, RecordComponent[] components, Class<?> leafType) {
    }
}
