name: Gradle Package

on:
  push:
    paths:
      - gradle.properties  # 当版本变更时触发
  workflow_dispatch:       # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 获取前一次提交以便比较

      - name: Compare mod_version
        id: version_check
        run: |
          CURRENT=$(grep "^mod_version=" gradle.properties | cut -d= -f2)
          PREVIOUS=$(git show HEAD^:gradle.properties | grep "^mod_version=" | cut -d= -f2)
          echo "Current version: $CURRENT"
          echo "Previous version: $PREVIOUS"
          if [ "$CURRENT" = "$PREVIOUS" ]; then
            echo "mod_version 没有变更，跳过后续步骤。"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "mod_version 有变更，继续执行。"
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit if no mod_version change
        if: steps.version_check.outputs.skip == 'true' && github.event_name != 'workflow_dispatch'
        run: |
          echo "跳过构建，因为 mod_version 没有变化且不是手动触发。"
          exit 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
